# Generated by Django 4.0.5 on 2022-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=20)),
                ('contact_reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='manuitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemimage', models.ImageField(upload_to='static/manuitems')),
                ('itemicons', models.ImageField(upload_to='static/manuicons')),
                ('itemprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='signup_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=20)),
                ('city_name', models.CharField(max_length=30)),
                ('contact_no', models.BigIntegerField()),
            ],
        ),
    ]
