# Generated by Django 4.0.5 on 2022-08-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='basket',
        ),
    ]
