# Generated by Django 4.0.5 on 2022-08-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manuitems',
        ),
    ]
