# Generated by Django 4.0.5 on 2022-08-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='basket',
        ),
    ]
